(lang dune 3.20)
(name exp_3)

(generate_opam_files true)

(maintainers "CSharperMantle <webmaster@csmantle.top>")

(package
 (name exp_3)
 (synopsis "Experiment 3")
 (depends
  (ocaml (= 5.4.0))
  ocaml-lsp-server
  ocamlformat
  utop))